name: Build luci-app-adguardhome for ARMv8
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev git gawk unzip
          wget https://downloads.immortalwrt.org/releases/24.10-SNAPSHOT/targets/armvirt/64/immortalwrt-sdk-24.10-armvirt-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xvf immortalwrt-sdk-*.tar.xz
          mv immortalwrt-sdk-* openwrt

      - name: Clone luci-app-adguardhome
        run: |
          git clone --depth=1 https://github.com/sirpdboy/luci-app-adguardhome.git openwrt/package/luci-app-adguardhome

      - name: Compile
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install libuci libubus
          echo "CONFIG_PACKAGE_luci-app-adguardhome=y" >> .config
          make defconfig
          make package/luci-app-adguardhome/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: adguardhome-ipk
          path: openwrt/bin/packages/aarch64_generic/luci/*.ipk
